name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy using Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
        CI: true
    - run: |
        # Build
        npm ci
        npm run build

        # Deploy
        cd ..
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws s3 sync ./studymandar.in/dist s3://studymandar.in

        # Invalidate cloudfront instance
        aws cloudfront create-invalidation \
            --distribution-id ECZDTVNGO7GS \
            --paths "/*"
